[versions]
kotlin = "2.2.0"
ktlint = "13.0.0"
junit = "5.13.3"
assertj = "3.27.6"
vertx = "5.0.2"
netty = "4.2.3.Final" # Should align with netty the version that Vert.x uses
dsljson = "2.0.2"

[libraries]
vertx-lang-kotlin = { group = "io.vertx", name = "vertx-lang-kotlin", version.ref = "vertx" }
vertx-web = { group = "io.vertx", name = "vertx-web", version.ref = "vertx" }
dsljson = { group = "com.dslplatform", name = "dsl-json", version.ref = "dsljson" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
